data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = c("?",""))
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data$timetemp <- paste(data$Date, data$Time)
data$Time <- strptime(data$timetemp, format = "%Y-%m-%d %H:%M:%S")
data <- subset(data , data$Date ==  "2007-02-01" | data$Date ==  "2007-02-02")
a$Time, data$Sub_metering_1, type = "l", ylab = "Energy sub metering"
lines(data$Time, data$Sub_metering_2, col = "red")
lines(data$Time, data$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()